name: Debug Directory Access on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug SSH Connection and Directory Access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
              echo "Now Inside Directory"
              cd /var/www/jaffery-backend
              git fetch origin
              git checkout main
              git pull origin main
            
              pm2 restart 0
            echo "Deployment successful!"
              
