name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 This allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /var/www/jaffery-backend
            git pull origin main
            npm install
            pm2 restart server.js
            echo "Deployment successful!"
