name: Debug Directory Access on VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug SSH Connection and Directory Access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            echo "Now Inside Directory"
            cd /var/www/jaffery-backend || exit 1

            echo "Fetching latest code from GitHub..."
            git fetch origin
            git checkout master
            git pull origin master

            echo "Restarting application with PM2..."
            pm2 restart 0

            echo "✅ Deployment successful!"
